harold-bank/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "accounts#show"
  resources :accounts
  post 'transfer', to: 'accounts#transfer'
  post 'deposit', to: 'accounts#deposit'

  resources :transactions
end

harold-bank/app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user

  has_many :origin_account, class_name: 'Account', foreign_key: 'origin_account_id'
  has_many :destination_account, class_name: 'Account', foreign_key: 'destination_account_id'

  validates :amount, numericality: { greater_than_or_equal_to: 0.0 }
  validates :user, presence: true

  def initialize(attributes = {})
    super

    self.account_number = SecureRandom.alphanumeric(5).upcase
  end

  def self.by_user_id(id)
    find_by(user_id: id)
  end

  def self.by_account_number(account_number)
    find_by(account_number: account_number)
  end

  def deposit(amount)
    Transaction.deposit_start(user, self, amount)
    if amount >= 0.0
      self.amount += amount
      if self.save!
        Transaction.deposit_successful(user, self, amount)
      else
        Transaction.deposit_failed(user, self, amount)
      end
    else
      self.errors[:base] << 'No destination account'
      Transaction.deposit_failed(user, self, amount)
    end
  end

  def transfer(destination, amount)
    destination_account = Account.by_account_number(destination)
    Transaction.transfer_start(user, self, destination_account, amount)
    if destination_account
      if funds_available?(amount)
        self.amount -= amount
        destination_account.amount += amount

        if save! && destination_account.save!
          Transaction.transfer_successful(user, self, destination_account, amount)
          return true
        else
          Transaction.transfer_failed(user, self, destination_account, amount)
          return false
        end
      else
        self.errors[:base] << 'No funds available'
        Transaction.transfer_failed(user, self, destination_account, amount)
        return false
      end
    else
      self.errors[:base] << 'No existing destination account'
      Transaction.transfer_failed(user, self, destination_account, amount)
      return false
    end
  end

  def withdraw(amount)
    if funds_available?(amount)
      self.amount -= amount
      self.save!
    else
      self.errors[:base] << 'No funds available'
    end
  end

  private

  def funds_available?(amount)
    self.amount >= amount
  end


end

harold-bank/app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!
  check_authorization
  load_and_authorize_resource :only => [:show, :transfer]

  before_action :get_account, only: %i[transfer show]

  def show
    if !current_user.admin?
      if @account
        get_transactions(@account)
      end
      respond_to :html
    else
      redirect_to action: 'index'
    end
  end

  def index
    authorize! :index, Account if current_user.admin?
    @accounts = Account.all
    respond_to :html
  end

  def new
    authorize! :new, Account if current_user.admin?
    @account = Account.new
  end

  def create
    authorize! :create, Account if current_user.admin?
    @account = Account.new(account_params)

    if @account.save
      flash[:notice] = 'Account successfully created'
      redirect_to action: 'index'
    else
      flash[:error] = 'Error creating account'
      render action: 'new'
    end
  end

  def transfer
    destination = transfer_params[:account_number]
    amount = transfer_params[:amount].to_f

    if @account.active? && @account.transfer(destination, amount)
      flash[:notice] = 'Successful transfer'
    else
      flash[:error] = "Transfer failed, error: #{ @account.errors.messages[:base][0] }"
    end
    redirect_to action: 'show'
  end

  def deposit
    authorize! :deposit, Account if current_user.admin?
    destination = transfer_params[:account_number]
    amount = transfer_params[:amount].to_f
    account = Account.by_account_number(destination)

    if account.deposit(amount)
      flash[:notice] = 'Successful deposit'
    else
      flash[:error] = "Deposit failed, error: #{ @account.errors.messages[:base][0] }"
    end
    redirect_to action: 'index'
  end

  private

  def get_account
    @account = Account.by_user_id(current_user.id)
  end

  def get_transactions(account)
    @transactions = Transaction.by_relation(account.id)
  end

  def transfer_params
    params.require(:transfer).permit(:account_number, :amount)
  end

  def account_params
    params.require(:account).permit(:user_id, :amount, :active)
  end

end

harold-bank/app/helpers/accounts_helper.rb
module AccountsHelper
end

harold-bank/app/views/accounts/index.html.erb
<div>
  <h4>
    Platform Accounts
  </h4>
  <table>
    <tr>
      <th>
        Username
      </th>
      <th>
        Account Number
      </th>
      <th>
        Active
      </th>
      <th>
        Amount
      </th>
    </tr>
    <% @accounts.each do |account| %>
      <tr>
        <td>
          <%= account.user.email %>
        </td>
        <td>
          <%= account.account_number %>
        </td>
        <td>
          <%= account.active ? "Yes" : "No" %>
        </td>
        <td>
          <%= account.amount %>
        </td>
      </tr>
    <% end %>
  </table>
</div>
<div>
  <%= link_to "New Account", new_account_path %>
</div>
<div>
  <%= link_to "All Transactions", transactions_path %>
</div>
<div>
  <div>
    <h4>
      Deposit to Account
    </h4>
  </div>
  <div>
    <%= form_for :transfer, url: { action: 'deposit' } do |f| %>
      <%= f.label :account_number, 'Account Number' %><br>
      <%= f.select :account_number, options_from_collection_for_select(Account.all, :account_number, :account_number) %><br><br>
      <%= f.label :amount, 'Amount' %><br>
      <%= f.number_field :amount, min: 0 %><br><br>
      <%= f.submit "Send Deposit" %>
    <% end %>
  </div>
</div>
<div>
  <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
</div>

harold-bank/app/views/accounts/new.html.erb
<div>
  <h4>
    New Account
  </h4>
</div>
<div>
  <%= form_for @account, url: { action: 'create' } do |f| %>
    <%= f.label :user, 'User' %><br>
    <%= f.select :user_id, options_from_collection_for_select(User.all, :id, :email) %><br><br>
    <%= f.label :amount, 'Initial Amount' %><br>
    <%= f.number_field :amount, min: 0 %><br><br>
    <%= f.label :active, 'Active' %><br>
    <%= f.select :active, [['Yes', true], ['No', false]]  %><br><br>
    <%= f.submit 'Create Account'  %>
  <% end %>
</div>

harold-bank/app/views/accounts/show.html.erb
<% if !@account.blank? %>
  <table>
    <tr>
      <th>
        Username
      </th>
      <th>
        Account Number
      </th>
      <th>
        Active
      </th>
      <th>
        Amount
      </th>
    </tr>
    <tr>
      <td>
        <%= @account.user.email %>
      </td>
      <td>
        <%= @account.account_number %>
      </td>
      <td>
        <%= @account.active ? "Yes" : "No" %>
      </td>
      <td>
        <%= @account.amount %>
      </td>
    </tr>
  </table>

  <div>
    <%= form_for :transfer, url: { action: 'transfer' } do |f| %>
      <%= f.label :account_number, 'Account Number' %><br>
      <%= f.select :account_number, options_from_collection_for_select(Account.all.select { |a| a.id != @account.id }, :account_number, :account_number) %>
      <%# f.text_field :account_number  %><br>
      <%= f.label :amount, 'Amount' %><br>
      <%= f.number_field :amount, min: 0 %><br><br>
      <%= f.submit "Send Transfer" %>
    <% end %>
  </div>

  <div>
    <div>
      <h4>
        Transactions
      </h4>
    </div>
    <div>
      <table>
        <tr>
          <th>
            Transaction Date
          </th>
          <th>
            Transaction Id
          </th>
          <th>
            Transaction Type
          </th>
          <th>
            Origin Account
          </th>
          <th>
            Destination Account
          </th>
          <th>
            Amount
          </th>
          <th>
            Status
          </th>
        </tr>
        <% @transactions.each do |transaction|  %>
          <tr>
            <td>
              <%= transaction.created_at.strftime('%d/%m/%Y %H:%M:%S') %>
            </td>
            <td>
              <%= transaction.id %>
            </td>
            <td>
              <%= transaction.action %>
            </td>
            <td>
              <%= @account.account_number == transaction.origin_account.account_number ? "My Account" : transaction.origin_account.account_number %>
            </td>
            <td>
              <%= @account.account_number == transaction.destination_account.account_number ? "My Account" : transaction.destination_account.account_number %>
            </td>
            <td>
              <%= transaction.action == "transfer" && @account.account_number == transaction.origin_account.account_number ? "-#{transaction.amount}": transaction.amount  %>
            </td>
            <td>
              <%= transaction.status  %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
<% else %>
  No account created, ask an administrator for a new account
<% end %>